Document: tartini
Title: Debian tartini Manual
Author: <insert document author here>
Abstract: This manual describes what tartini is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tartini/tartini.sgml.gz

Format: postscript
Files: /usr/share/doc/tartini/tartini.ps.gz

Format: text
Files: /usr/share/doc/tartini/tartini.text.gz

Format: HTML
Index: /usr/share/doc/tartini/html/index.html
Files: /usr/share/doc/tartini/html/*.html
